# config file for the entire solution

# data output settings
TRANSFORMED_DATA_PATH = "interim_data/"

# calculation settings
NUMBER_OF_MFCC = 20

NUMBER_OF_CPU_IN_POOL = 6

# Fourier Transform Settings
# Default FFT window size
N_FFT = 2048  # FFT window size
HOP_LENGTH = 512  # number audio of frames between STFT columns (looks like a good default)

# classification labels
LABELS = ['Alder Flycatcher', 'American Avocet', 'American Bittern', 'American Crow',
          'American Goldfinch', 'American Kestrel', 'Buff-bellied Pipit',
          'American Redstart', 'American Robin', 'American Wigeon',
          'American Woodcock', 'American Tree Sparrow', "Anna's Hummingbird",
          'Ash-throated Flycatcher', "Baird's Sandpiper", 'Bald Eagle',
          'Baltimore Oriole', 'Sand Martin', 'Barn Swallow', 'Black-and-white Warbler',
          'Belted Kingfisher', "Bell's Sparrow", "Bewick's Wren",
          'Black-billed Cuckoo', 'Black-billed Magpie', 'Blackburnian Warbler',
          'Black-capped Chickadee', 'Black-chinned Hummingbird',
          'Black-headed Grosbeak', 'Blackpoll Warbler', 'Black-throated Sparrow',
          'Black Phoebe', 'Blue Grosbeak', 'Blue Jay', 'Brown-headed Cowbird',
          'Bobolink', "Bonaparte's Gull", 'Barred Owl', "Brewer's Blackbird",
          "Brewer's Sparrow", 'Brown Creeper', 'Brown Thrasher',
          'Broad-tailed Hummingbird', 'Broad-winged Hawk',
          'Black-throated Blue Warbler', 'Black-throated Green Warbler',
          'Black-throated Grey Warbler', 'Bufflehead', 'Blue-grey Gnatcatcher',
          'Blue-headed Vireo', "Bullock's Oriole", 'American Bushtit',
          'Blue-winged Teal', 'Blue-winged Warbler', 'Cactus Wren', 'California Gull',
          'California Quail', 'Cape May Warbler', 'Canada Goose', 'Canada Warbler',
          'Canyon Wren', 'Carolina Wren', "Cassin's Finch", 'Caspian Tern',
          "Cassin's Vireo", 'Cedar Waxwing', 'Chipping Sparrow', 'Chimney Swift',
          'Chestnut-sided Warbler', 'Chukar Partridge', "Clark's Nutcracker",
          'American Cliff Swallow', 'Common Goldeneye', 'Common Grackle',
          'Common Loon', 'Common Merganser', 'Common Nighthawk', 'Northern Raven',
          'Common Redpoll', 'Common Tern', 'Common Yellowthroat', "Cooper's Hawk",
          "Costa's Hummingbird", 'California Scrub Jay', 'Dark-eyed Junco',
          'Double-crested Cormorant', 'Downy Woodpecker', 'American Dusky Flycatcher',
          'Black-necked Grebe', 'Eastern Bluebird', 'Eastern Kingbird',
          'Eastern Meadowlark', 'Eastern Phoebe', 'Eastern Towhee',
          'Eastern Wood Pewee', 'Eurasian Collared Dove', 'Common Starling',
          'Evening Grosbeak', 'Field Sparrow', 'Fish Crow', 'Red Fox Sparrow',
          'Gadwall', 'Grey-crowned Rosy Finch', 'Green-tailed Towhee', 'Eurasian Teal',
          'Golden-crowned Kinglet', 'Golden-crowned Sparrow', 'Golden Eagle',
          'Great Blue Heron', 'Great Crested Flycatcher', 'Great Egret',
          'Greater Roadrunner', 'Greater Yellowlegs', 'Great Horned Owl',
          'Green Heron', 'Great-tailed Grackle', 'Grey Catbird',
          'American Grey Flycatcher', 'Hairy Woodpecker', "Hammond's Flycatcher",
          'European Herring Gull', 'Hermit Thrush', 'Hooded Merganser',
          'Hooded Warbler', 'Horned Grebe', 'Horned Lark', 'House Finch',
          'House Sparrow', 'House Wren', 'Indigo Bunting', 'Juniper Titmouse',
          'Killdeer', 'Ladder-backed Woodpecker', 'Lark Sparrow', 'Lazuli Bunting',
          'Least Bittern', 'Least Flycatcher', 'Least Sandpiper', "LeConte's Thrasher",
          'Lesser Goldfinch', 'Lesser Nighthawk', 'Lesser Yellowlegs',
          "Lewis's Woodpecker", "Lincoln's Sparrow", 'Long-billed Curlew',
          'Long-billed Dowitcher', 'Loggerhead Shrike', 'Long-tailed Duck',
          'Louisiana Waterthrush', "MacGillivray's Warbler", 'Magnolia Warbler',
          'Mallard', 'Marsh Wren', 'Merlin', 'Mountain Bluebird', 'Mountain Chickadee',
          'Mourning Dove', 'Northern Cardinal', 'Northern Flicker', 'Northern Harrier',
          'Northern Mockingbird', 'Northern Parula', 'Northern Pintail',
          'Northern Shoveler', 'Northern Waterthrush',
          'Northern Rough-winged Swallow', "Nuttall's Woodpecker",
          'Olive-sided Flycatcher', 'Orange-crowned Warbler', 'Western Osprey',
          'Ovenbird', 'Palm Warbler', 'Pacific-slope Flycatcher', 'Pectoral Sandpiper',
          'Peregrine Falcon', 'Phainopepla', 'Pied-billed Grebe',
          'Pileated Woodpecker', 'Pine Grosbeak', 'Pinyon Jay', 'Pine Siskin',
          'Pine Warbler', 'Plumbeous Vireo', 'Prairie Warbler', 'Purple Finch',
          'Pygmy Nuthatch', 'Red-breasted Merganser', 'Red-breasted Nuthatch',
          'Red-breasted Sapsucker', 'Red-bellied Woodpecker', 'Red Crossbill',
          'Redhead', 'Red-eyed Vireo', 'Red-necked Phalarope', 'Red-shouldered Hawk',
          'Red-tailed Hawk', 'Red-winged Blackbird', 'Ring-billed Gull',
          'Ring-necked Duck', 'Rose-breasted Grosbeak', 'Rock Dove', 'Rock Wren',
          'Ruby-throated Hummingbird', 'Ruby-crowned Kinglet', 'Ruddy Duck',
          'Ruffed Grouse', 'Rufous Hummingbird', 'Rusty Blackbird',
          'Sagebrush Sparrow', 'Sage Thrasher', 'Savannah Sparrow', "Say's Phoebe",
          'Scarlet Tanager', "Scott's Oriole", 'Semipalmated Plover',
          'Semipalmated Sandpiper', 'Short-eared Owl', 'Sharp-shinned Hawk',
          'Snow Bunting', 'Snow Goose', 'Solitary Sandpiper', 'Song Sparrow', 'Sora',
          'Spotted Sandpiper', 'Spotted Towhee', "Steller's Jay", "Swainson's Hawk",
          'Swamp Sparrow', "Swainson's Thrush", 'Tree Swallow', 'Trumpeter Swan',
          'Tufted Titmouse', 'Tundra Swan', 'Veery', 'Vesper Sparrow',
          'Violet-green Swallow', 'Warbling Vireo', 'Western Bluebird',
          'Western Grebe', 'Western Kingbird', 'Western Meadowlark',
          'Western Sandpiper', 'Western Tanager', 'Western Wood Pewee',
          'White-breasted Nuthatch', 'White-crowned Sparrow', 'White-faced Ibis',
          'White-throated Sparrow', 'White-throated Swift', 'Willow Flycatcher',
          "Wilson's Snipe", 'Wild Turkey', 'Winter Wren', "Wilson's Warbler",
          'Wood Duck', "Woodhouse's Scrub Jay", 'Wood Thrush', 'American Coot',
          'Yellow-bellied Flycatcher', 'Yellow-bellied Sapsucker',
          'Yellow-headed Blackbird', 'Mangrove Warbler', 'Myrtle Warbler',
          'Yellow-throated Vireo']
